### ISSUE TITLE
Include session creation in measured time

### ISSUE THREAD

**Issue by pingtimeout** [datastax/gatling-dse-plugin#4]
Some session values are expensive to compute.  A 6.0 example is building the fluent traversals.

In `DseRequestAction`, we start measuring the latency [just before sending the request](https://github.com/datastax/gatling-dse-plugin/blob/master/src/main/scala/com/datastax/gatling/plugin/request/DseRequestAction.scala#L82).  It is the correct thing to do.

However, [this code block](https://github.com/datastax/gatling-dse-plugin/blob/master/src/main/scala/com/datastax/gatling/plugin/request/DseRequestAction.scala#L62-L67) can take a significant (think tens of millis) amount of time.  In these cases, it can be puzzling for users to understand what happened.

We should add the ability to record the time spent in gatling per-se and report it after the test

**Comment by pingtimeout** [comment]
@tlasica ran into this issue in Search workloads.  They use the faker library which calls web service (!) during data generation (i.e. from the feeder).  Reporting feeder time becomes more and more important.

Also we might want to consider some safety check, like "if building the test data took more than 5~10ms, fail the query even before sending it"

**Comment by tlasica** [comment]
Seems I was wrong about the web service - It reads from yaml files.
Still terribly slow.

**Comment by pingtimeout** [comment]
Fixed in #7 since we now rely on gatling start time for each request instead of our own
